"""Initial complete schema: college, college_setting, module_config, users

Revision ID: 124ea016ac81
Revises: 
Create Date: 2026-08-21 17:48:04.245479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124ea016ac81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_college_slug'), ['slug'], unique=True)

    op.create_table('college_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('college_name', sa.String(length=150), nullable=True),
    sa.Column('tagline', sa.String(length=250), nullable=True),
    sa.Column('logo_path', sa.String(length=250), nullable=True),
    sa.Column('email_info', sa.String(length=120), nullable=True),
    sa.Column('phone_primary', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('accreditation', sa.String(length=100), nullable=True),
    sa.Column('hero_title', sa.String(length=150), nullable=True),
    sa.Column('hero_subtitle', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id')
    )
    op.create_table('module_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('admin_access', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'module_key', name='uix_college_module_key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('module_config')
    op.drop_table('college_setting')
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_college_slug'))

    op.drop_table('college')
    # ### end Alembic commands ###
