"""Add course and curriculum models

Revision ID: 1a86bd0c3691
Revises: fbd4e8739640
Create Date: 2026-08-22 12:58:06.832225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a86bd0c3691'
down_revision = 'fbd4e8739640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('affiliation', sa.String(length=150), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('eligibility', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'code', name='uq_course_college_code')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_college_id'), ['college_id'], unique=False)

    op.create_table('course_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_outcomes_course_id'), ['course_id'], unique=False)

    op.create_table('curriculum_semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester_name', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curriculum_semesters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_semesters_course_id'), ['course_id'], unique=False)

    op.create_table('question_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('filename', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_papers_course_id'), ['course_id'], unique=False)

    op.create_table('curriculum_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=150), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['curriculum_semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curriculum_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_subjects_semester_id'), ['semester_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculum_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_subjects_semester_id'))

    op.drop_table('curriculum_subjects')
    with op.batch_alter_table('question_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_papers_course_id'))

    op.drop_table('question_papers')
    with op.batch_alter_table('curriculum_semesters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_semesters_course_id'))

    op.drop_table('curriculum_semesters')
    with op.batch_alter_table('course_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_outcomes_course_id'))

    op.drop_table('course_outcomes')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_college_id'))

    op.drop_table('courses')
    # ### end Alembic commands ###
