"""Add AdmissionApplication model

Revision ID: 2a1c0135a0b4
Revises: 124ea016ac81
Create Date: 2026-08-21 18:31:45.981407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1c0135a0b4'
down_revision = '124ea016ac81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('guardian_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('course', sa.String(length=150), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admission_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admission_applications_application_number'), ['application_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admission_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admission_applications_application_number'))

    op.drop_table('admission_applications')
    # ### end Alembic commands ###
