"""add_indexes_to_admission_and_gallery

Revision ID: b3f9dc25698d
Revises: b49d8281eeaa
Create Date: 2026-08-22 15:02:48.964607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f9dc25698d'
down_revision = 'b49d8281eeaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admission_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admission_applications_college_id'), ['college_id'], unique=False)

    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_items_college_id'), ['college_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_items_college_id'))

    with op.batch_alter_table('admission_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admission_applications_college_id'))

    # ### end Alembic commands ###
