"""Add campus_events and academic_calendar_items models

Revision ID: b49d8281eeaa
Revises: 1a86bd0c3691
Create Date: 2026-08-22 13:59:51.660112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49d8281eeaa'
down_revision = '1a86bd0c3691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_calendar_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('date_display', sa.String(length=100), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_calendar_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_calendar_items_college_id'), ['college_id'], unique=False)

    op.create_table('campus_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('date_display', sa.String(length=100), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campus_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campus_events_college_id'), ['college_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campus_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campus_events_college_id'))

    op.drop_table('campus_events')
    with op.batch_alter_table('academic_calendar_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_calendar_items_college_id'))

    op.drop_table('academic_calendar_items')
    # ### end Alembic commands ###
